### ISSUE TITLE
Composition error message regression 

### ISSUE THREAD

**Issue by clenfest** [apollographql/federation#2621]
### Issue Description

It seems like there is an issue with composition errors in the latest 2.4.7. Rather than getting a composition error, I'm getting a typescript error.

2.4.3:
```
➜ rover supergraph compose --config sg.yaml
⌛ resolving SDL for subgraphs defined in sg.yaml
🎶 composing supergraph with Federation v2.4.3
error[E029]: Encountered 1 build error while trying to build a supergraph.

Caused by:
    UNKNOWN: The following supergraph API query:
    subscription {
      onNewUser {
        description
      }
    }
    cannot be satisfied by the subgraphs because:
    - from subgraph "A":
      - cannot find field "User.description".
      - cannot move to subgraph "B", which has field "User.description", because type "User" has no @key defined in subgraph "B".

        The subgraph schemas you provided are incompatible with each other. See https://www.apollographql.com/docs/federation/errors/ for more information on resolving build errors.
```

2.4.7:
```
➜ rover supergraph compose --config sg.yaml
⌛ resolving SDL for subgraphs defined in sg.yaml
🎶 composing supergraph with Federation v2.4.7
error[E029]: Encountered 1 build error while trying to build a supergraph.

Caused by:
    UNKNOWN: TypeError: Cannot read properties of undefined (reading 'map')

        The subgraph schemas you provided are incompatible with each other. See https://www.apollographql.com/docs/federation/errors/ for more information on resolving build errors.
```

### Link to Reproduction

n/a

### Reproduction Steps

```graphql
type User {
  id: ID!
  name: String!
}

type Query {
  allUsers: [User!]!
}
```

```graphql
type User {
  id: ID!
  name: String!
  description: String!
}

type Query {
  getUser(id: ID!): User!
}
```

```
federation_version: =2.4.7
subgraphs:
  # Local .graphql file
  A:
    routing_url: http://localhost:4001
    schema:
      file: ./A.graphql

  B:
    routing_url: http://localhost:4002
    schema:
      file: ./B.graphql
```
