### ISSUE TITLE
Requesting the ability to set timeout/retry on subgraph requests.

### ISSUE THREAD

**Issue by sangyeol-kim** [apollographql/federation#2647]
I would appreciate any insights/thoughts about this, before we/or someone else contributes an implementation.

Feature Request

I want to apply timeout to subgraph request.
make-fetch-happen seems to be utilized only for uplinks.

Background

If I configure the gateway through apollo federation, I want to set timeout and retry of subgraph at supergraph config level.

Proposal

The feature you are requesting is to set the subgraph's timeout at the supergraph config level like so:

(I tried to find those functions, but I understood that traffic_shaping and make-fetch-happen are only utilized for uplinks and not for subgraph requests. If these functions already exist, please help me.)

```
federation_version: =2.1.4
subgraphs:
  local:
    routing_url: local
    schema:
      file: ../app/graphql/local.graphql
    timeout: 5s
    retry: 1
```
